### ISSUE TITLE
Variable width

### ISSUE THREAD

**Issue by wmertens** [treyhoover/react-sliderp#1]
Would it be possible to make the slides variable width? The use case is photographs with varying aspect ratios, but the slider has to stay the same height.

It could even be that a slide is wider than the slider.

For determining the size there would have to be some callback mechanism, the size is only known after loading…

**Comment by treyhoover** [comment]
Hm, it should be possible. Perhaps we could leverage react-virtualized's [CellMeasurer](https://github.com/bvaughn/react-virtualized/blob/master/docs/CellMeasurer.md) component.
